### ISSUE TITLE
Java语法糖.md 拼写错误

### ISSUE THREAD

**Issue by anaer** [Java-Edge/Java-Interview-Tutorial#4]
![image](https://user-images.githubusercontent.com/4637100/126606084-f8c04a22-7c18-4be9-9dfe-45aba3a1efc7.png)
![image](https://user-images.githubusercontent.com/4637100/126606257-fee9cb3d-0d71-4f3d-9b54-e404b04eb44a.png)

**Comment by Java-Edge** [comment]
已修正！
